/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * logforserver.java
 *
 * Created on Jan 25, 2016, 9:19:49 PM
 */

package massengerbyme;
import java.sql.*;
/**
 *
 * @author Rakibul
 */

public class logforserver extends javax.swing.JFrame {
DatabaseTest dt;
    /** Creates new form logforserver */
    public logforserver(DatabaseTest dt) {
        this.dt=dt;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(massengerbyme.MassengerbymeApp.class).getContext().getResourceMap(logforserver.class);
        jPanel1.setBackground(resourceMap.getColor("jPanel1.background")); // NOI18N
        jPanel1.setForeground(resourceMap.getColor("jPanel1.foreground")); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(null);

        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(140, 40, 150, 14);

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 120, 90, 14);

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 180, 80, 14);

        jTextField1.setText(resourceMap.getString("jTextField1.text")); // NOI18N
        jTextField1.setName("jTextField1"); // NOI18N
        jPanel1.add(jTextField1);
        jTextField1.setBounds(140, 110, 170, 40);

        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(220, 250, 79, 23);

        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N
        jPanel1.add(jButton2);
        jButton2.setBounds(29, 250, 140, 23);

        jPasswordField1.setText(resourceMap.getString("jPasswordField1.text")); // NOI18N
        jPasswordField1.setName("jPasswordField1"); // NOI18N
        jPanel1.add(jPasswordField1);
        jPasswordField1.setBounds(140, 170, 170, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   Full_name=jTextField1.getText();
   Password=jPasswordField1.getText();
   try{
               if(jTextField1.getText().equals("") && jPasswordField1.getText().equals(""))
             {
                 jp.showMessageDialog(jf,"Enter Fullname and Password");
             }

            else if(jTextField1.getText().equals(""))
                 {
                     jp.showMessageDialog(jf,"input Full name !");
                 }
              else if(jPasswordField1.getText().equals(""))
                 {
                      jp.showMessageDialog(jf,"input password !");
                 }
          ResultSet rs=dt.dbc.searchDB("select * from sdb where Full_name='"+Full_name+"'");
          int flag =0;
          while(rs.next()){
          if(rs.getString("Full_name").equals(Full_name) && rs.getString("Password").equals(Password)){
              jp.showMessageDialog(jf, "Login Successful");
              flag = 1;
              this.setVisible(false);
              chatofserver cs=new chatofserver();
              chatofclint ct=new chatofclint();
              cs.setVisible(true);
              ct.setVisible(true);
          }
              if(flag == 0)
                  jp.showMessageDialog(jf, "Invalid log in");
            break;
          }

          rs.close();


          }catch(Exception e){
              System.out.println("problem");
          }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */

    public String Full_name=new String();
    public String Password=new String();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
 public javax.swing.JOptionPane jp;
    public javax.swing.JFrame jf;
}
