/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Showinformation.java
 *
 * Created on Dec 30, 2015, 2:40:35 AM
 */

package projectdemo;
import java.sql.*;
/**
 *
 * @author Rakibul
 */
public class Showinformation extends javax.swing.JFrame {
public DatabaseTest dt;
ProjectDemoView pd;
//public String NID=new String();
//public String Password=new String();
    /** Creates new form Showinformation */
    public Showinformation(DatabaseTest dt,ProjectDemoView pd) {
        this.dt=dt;
        this.pd=pd;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(projectdemo.ProjectDemoApp.class).getContext().getResourceMap(Showinformation.class);
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N

        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(null);

        jButton1.setBackground(resourceMap.getColor("jButton1.background")); // NOI18N
        jButton1.setFont(resourceMap.getFont("jButton4.font")); // NOI18N
        jButton1.setForeground(resourceMap.getColor("jButton1.foreground")); // NOI18N
        jButton1.setIcon(resourceMap.getIcon("jButton1.icon")); // NOI18N
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(120, 310, 160, 40);

        jButton2.setBackground(resourceMap.getColor("jButton2.background")); // NOI18N
        jButton2.setFont(resourceMap.getFont("jButton4.font")); // NOI18N
        jButton2.setForeground(resourceMap.getColor("jButton1.foreground")); // NOI18N
        jButton2.setIcon(resourceMap.getIcon("jButton2.icon")); // NOI18N
        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(290, 310, 180, 40);

        jButton3.setBackground(resourceMap.getColor("jButton3.background")); // NOI18N
        jButton3.setFont(resourceMap.getFont("jButton4.font")); // NOI18N
        jButton3.setForeground(resourceMap.getColor("jButton1.foreground")); // NOI18N
        jButton3.setIcon(resourceMap.getIcon("jButton3.icon")); // NOI18N
        jButton3.setText(resourceMap.getString("jButton3.text")); // NOI18N
        jButton3.setName("jButton3"); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(480, 310, 200, 40);

        jLabel1.setBackground(resourceMap.getColor("jLabel1.background")); // NOI18N
        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setForeground(resourceMap.getColor("jLabel1.foreground")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(280, 140, 450, 44);

        jButton4.setBackground(resourceMap.getColor("jButton4.background")); // NOI18N
        jButton4.setFont(resourceMap.getFont("jButton4.font")); // NOI18N
        jButton4.setIcon(resourceMap.getIcon("jButton4.icon")); // NOI18N
        jButton4.setText(resourceMap.getString("jButton4.text")); // NOI18N
        jButton4.setName("jButton4"); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(690, 310, 130, 40);

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(820, 140, 0, 0);

        jLabel4.setIcon(resourceMap.getIcon("jLabel4.icon")); // NOI18N
        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, -250, 960, 780);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 952, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  //      ProjectDemoView p=new ProjectDemoView();
        view v=new view(dt,pd);
        this.setVisible(false);
        v.setVisible(true);
        try{
        //ResultSet rs=dt.dbc.searchDB("select username from sdb where NID='"+id+"'");
        ResultSet rs=dt.dbc.searchDB("select * from sdb where NID='"+pd.NID+"' and Password='"+pd.password+"'");
        while(rs.next())
        {
            v.id = rs.getString("NID");
            v.fullname = rs.getString("Full_name");
            v.password = rs.getString("Password");
            v.Securityword = rs.getString("securityword");
            v.gender = rs.getString("gender");
            v.email = rs.getString("email");
            v.contact = rs.getString("contact");
            v.semester = rs.getString("semester");
            v.year = rs.getString("year");
            v.state = rs.getString("state");
            v.district = rs.getString("district");
            v.date = rs.getString("date");
            v.jLabel6.setText(v.id);
            v.jLabel7.setText(v.fullname);
            v.jLabel15.setText(v.password);
            v.jLabel16.setText(v.Securityword);
            v.jLabel20.setText(v.gender);
            v.jLabel21.setText(v.email);
            v.jLabel22.setText(v.contact);
            v.jLabel23.setText(v.semester);
            v.jLabel24.setText(v.year);
            v.jLabel25.setText(v.state);
            v.jLabel26.setText(v.district);
            v.jLabel27.setText(v.date);
        }
       }
       catch(Exception e){
            System.out.println("ping");
        }// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        update up=new update(pd,dt);
        this.setVisible(false);
        up.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int p=jp.showConfirmDialog(null,"Do You really want to delete?","Delete",jp.YES_NO_OPTION);
        if (p==0)
        {

        id=pd.NID;
        try{
        dt.dbc.updateDB("delete from sdb where NID='"+pd.NID+"'");
        jp.showMessageDialog(jp,"Delete Successful");
        this.setVisible(false);
        ProjectDemoApp.getApplication().getMainFrame().setVisible(true);
        pd.jTextField1.setText("");
        pd.jPasswordField1.setText("");
        }catch(Exception e){
            System.out.println("ping");
        }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.setVisible(false);
        ProjectDemoApp.getApplication().getMainFrame().setVisible(true);
        pd.jTextField1.setText("");
        pd.jPasswordField1.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
    * @param args the command line arguments
    */
    public String id=new String();
   /* public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
               new Showinformation().setVisible(true);
            }
        });

    }
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
 public javax.swing.JOptionPane jp;
    public javax.swing.JFrame jf;
}
