/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * view.java
 *
 * Created on Jan 3, 2016, 12:28:36 AM
 */

package projectdemo;

/**
 *
 * @author Rakibul
 */
import java.sql.*;
public class view extends javax.swing.JFrame {
private DatabaseTest dt;
ProjectDemoView pd;
    /** Creates new form view */
    public view(DatabaseTest dt,ProjectDemoView pd) {
        this.dt=dt;
        this.pd=pd;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();

        jPanel1.setName("jPanel1"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(projectdemo.ProjectDemoApp.class).getContext().getResourceMap(view.class);
        jLabel28.setFont(resourceMap.getFont("jLabel14.font")); // NOI18N
        jLabel28.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rakibul\\Downloads\\hd-wallpapers-1080p-for-mobile.png")); // NOI18N
        jLabel28.setText(resourceMap.getString("jLabel28.text")); // NOI18N
        jLabel28.setName("jLabel28"); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N

        jPanel2.setName("jPanel2"); // NOI18N
        jPanel2.setLayout(null);

        jLabel1.setBackground(resourceMap.getColor("jLabel14.background")); // NOI18N
        jLabel1.setFont(resourceMap.getFont("jLabel14.font")); // NOI18N
        jLabel1.setForeground(resourceMap.getColor("jLabel14.foreground")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(50, 80, 110, 30);

        jLabel3.setBackground(resourceMap.getColor("jLabel14.background")); // NOI18N
        jLabel3.setFont(resourceMap.getFont("jLabel14.font")); // NOI18N
        jLabel3.setForeground(resourceMap.getColor("jLabel14.foreground")); // NOI18N
        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N
        jPanel2.add(jLabel3);
        jLabel3.setBounds(50, 110, 120, 50);

        jLabel4.setBackground(resourceMap.getColor("jLabel14.background")); // NOI18N
        jLabel4.setFont(resourceMap.getFont("jLabel14.font")); // NOI18N
        jLabel4.setForeground(resourceMap.getColor("jLabel14.foreground")); // NOI18N
        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N
        jPanel2.add(jLabel4);
        jLabel4.setBounds(50, 160, 120, 30);

        jLabel9.setBackground(resourceMap.getColor("jLabel14.background")); // NOI18N
        jLabel9.setFont(resourceMap.getFont("jLabel14.font")); // NOI18N
        jLabel9.setForeground(resourceMap.getColor("jLabel14.foreground")); // NOI18N
        jLabel9.setText(resourceMap.getString("jLabel9.text")); // NOI18N
        jLabel9.setName("jLabel9"); // NOI18N
        jPanel2.add(jLabel9);
        jLabel9.setBounds(50, 200, 110, 30);

        jLabel8.setBackground(resourceMap.getColor("jLabel14.background")); // NOI18N
        jLabel8.setFont(resourceMap.getFont("jLabel14.font")); // NOI18N
        jLabel8.setForeground(resourceMap.getColor("jLabel14.foreground")); // NOI18N
        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N
        jPanel2.add(jLabel8);
        jLabel8.setBounds(50, 240, 120, 30);

        jLabel12.setBackground(resourceMap.getColor("jLabel14.background")); // NOI18N
        jLabel12.setFont(resourceMap.getFont("jLabel14.font")); // NOI18N
        jLabel12.setForeground(resourceMap.getColor("jLabel14.foreground")); // NOI18N
        jLabel12.setText(resourceMap.getString("jLabel12.text")); // NOI18N
        jLabel12.setName("jLabel12"); // NOI18N
        jPanel2.add(jLabel12);
        jLabel12.setBounds(50, 280, 120, 30);

        jLabel11.setBackground(resourceMap.getColor("jLabel14.background")); // NOI18N
        jLabel11.setFont(resourceMap.getFont("jLabel14.font")); // NOI18N
        jLabel11.setForeground(resourceMap.getColor("jLabel14.foreground")); // NOI18N
        jLabel11.setText(resourceMap.getString("jLabel11.text")); // NOI18N
        jLabel11.setName("jLabel11"); // NOI18N
        jPanel2.add(jLabel11);
        jLabel11.setBounds(50, 320, 120, 30);

        jLabel13.setBackground(resourceMap.getColor("jLabel14.background")); // NOI18N
        jLabel13.setFont(resourceMap.getFont("jLabel14.font")); // NOI18N
        jLabel13.setForeground(resourceMap.getColor("jLabel14.foreground")); // NOI18N
        jLabel13.setText(resourceMap.getString("jLabel13.text")); // NOI18N
        jLabel13.setName("jLabel13"); // NOI18N
        jPanel2.add(jLabel13);
        jLabel13.setBounds(50, 360, 130, 30);

        jLabel14.setBackground(resourceMap.getColor("jLabel14.background")); // NOI18N
        jLabel14.setFont(resourceMap.getFont("jLabel14.font")); // NOI18N
        jLabel14.setForeground(resourceMap.getColor("jLabel14.foreground")); // NOI18N
        jLabel14.setText(resourceMap.getString("jLabel14.text")); // NOI18N
        jLabel14.setName("jLabel14"); // NOI18N
        jPanel2.add(jLabel14);
        jLabel14.setBounds(50, 400, 120, 30);

        jLabel2.setFont(resourceMap.getFont("jLabel2.font")); // NOI18N
        jLabel2.setForeground(resourceMap.getColor("jLabel2.foreground")); // NOI18N
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(90, 20, 240, 30);

        jButton1.setFont(resourceMap.getFont("jButton1.font")); // NOI18N
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(220, 580, 100, 40);

        jLabel6.setBackground(resourceMap.getColor("jLabel14.background")); // NOI18N
        jLabel6.setForeground(resourceMap.getColor("jLabel14.foreground")); // NOI18N
        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N
        jPanel2.add(jLabel6);
        jLabel6.setBounds(170, 80, 160, 30);

        jLabel7.setBackground(resourceMap.getColor("jLabel14.background")); // NOI18N
        jLabel7.setForeground(resourceMap.getColor("jLabel14.foreground")); // NOI18N
        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N
        jPanel2.add(jLabel7);
        jLabel7.setBounds(170, 120, 170, 30);

        jLabel15.setBackground(resourceMap.getColor("jLabel14.background")); // NOI18N
        jLabel15.setForeground(resourceMap.getColor("jLabel14.foreground")); // NOI18N
        jLabel15.setText(resourceMap.getString("jLabel15.text")); // NOI18N
        jLabel15.setName("jLabel15"); // NOI18N
        jPanel2.add(jLabel15);
        jLabel15.setBounds(170, 160, 190, 30);

        jLabel16.setBackground(resourceMap.getColor("jLabel14.background")); // NOI18N
        jLabel16.setForeground(resourceMap.getColor("jLabel14.foreground")); // NOI18N
        jLabel16.setText(resourceMap.getString("jLabel16.text")); // NOI18N
        jLabel16.setName("jLabel16"); // NOI18N
        jPanel2.add(jLabel16);
        jLabel16.setBounds(170, 200, 190, 30);

        jLabel17.setBackground(resourceMap.getColor("jLabel14.background")); // NOI18N
        jLabel17.setFont(resourceMap.getFont("jLabel14.font")); // NOI18N
        jLabel17.setForeground(resourceMap.getColor("jLabel14.foreground")); // NOI18N
        jLabel17.setText(resourceMap.getString("jLabel17.text")); // NOI18N
        jLabel17.setName("jLabel17"); // NOI18N
        jPanel2.add(jLabel17);
        jLabel17.setBounds(50, 520, 120, 30);

        jLabel18.setBackground(resourceMap.getColor("jLabel14.background")); // NOI18N
        jLabel18.setFont(resourceMap.getFont("jLabel14.font")); // NOI18N
        jLabel18.setForeground(resourceMap.getColor("jLabel14.foreground")); // NOI18N
        jLabel18.setText(resourceMap.getString("jLabel18.text")); // NOI18N
        jLabel18.setName("jLabel18"); // NOI18N
        jPanel2.add(jLabel18);
        jLabel18.setBounds(50, 440, 110, 30);

        jLabel19.setBackground(resourceMap.getColor("jLabel14.background")); // NOI18N
        jLabel19.setFont(resourceMap.getFont("jLabel14.font")); // NOI18N
        jLabel19.setForeground(resourceMap.getColor("jLabel14.foreground")); // NOI18N
        jLabel19.setText(resourceMap.getString("jLabel19.text")); // NOI18N
        jLabel19.setName("jLabel19"); // NOI18N
        jPanel2.add(jLabel19);
        jLabel19.setBounds(50, 480, 120, 30);

        jLabel20.setBackground(resourceMap.getColor("jLabel14.background")); // NOI18N
        jLabel20.setForeground(resourceMap.getColor("jLabel14.foreground")); // NOI18N
        jLabel20.setText(resourceMap.getString("jLabel20.text")); // NOI18N
        jLabel20.setName("jLabel20"); // NOI18N
        jPanel2.add(jLabel20);
        jLabel20.setBounds(170, 240, 100, 30);

        jLabel21.setBackground(resourceMap.getColor("jLabel14.background")); // NOI18N
        jLabel21.setForeground(resourceMap.getColor("jLabel14.foreground")); // NOI18N
        jLabel21.setText(resourceMap.getString("jLabel21.text")); // NOI18N
        jLabel21.setName("jLabel21"); // NOI18N
        jPanel2.add(jLabel21);
        jLabel21.setBounds(170, 280, 190, 30);

        jLabel22.setBackground(resourceMap.getColor("jLabel14.background")); // NOI18N
        jLabel22.setForeground(resourceMap.getColor("jLabel14.foreground")); // NOI18N
        jLabel22.setText(resourceMap.getString("jLabel22.text")); // NOI18N
        jLabel22.setName("jLabel22"); // NOI18N
        jPanel2.add(jLabel22);
        jLabel22.setBounds(170, 320, 160, 30);

        jLabel23.setBackground(resourceMap.getColor("jLabel14.background")); // NOI18N
        jLabel23.setForeground(resourceMap.getColor("jLabel14.foreground")); // NOI18N
        jLabel23.setText(resourceMap.getString("jLabel23.text")); // NOI18N
        jLabel23.setName("jLabel23"); // NOI18N
        jPanel2.add(jLabel23);
        jLabel23.setBounds(170, 360, 80, 30);

        jLabel24.setBackground(resourceMap.getColor("jLabel14.background")); // NOI18N
        jLabel24.setForeground(resourceMap.getColor("jLabel14.foreground")); // NOI18N
        jLabel24.setText(resourceMap.getString("jLabel24.text")); // NOI18N
        jLabel24.setName("jLabel24"); // NOI18N
        jPanel2.add(jLabel24);
        jLabel24.setBounds(170, 400, 70, 30);

        jLabel25.setBackground(resourceMap.getColor("jLabel14.background")); // NOI18N
        jLabel25.setForeground(resourceMap.getColor("jLabel14.foreground")); // NOI18N
        jLabel25.setText(resourceMap.getString("jLabel25.text")); // NOI18N
        jLabel25.setName("jLabel25"); // NOI18N
        jPanel2.add(jLabel25);
        jLabel25.setBounds(170, 440, 110, 30);

        jLabel26.setBackground(resourceMap.getColor("jLabel14.background")); // NOI18N
        jLabel26.setForeground(resourceMap.getColor("jLabel14.foreground")); // NOI18N
        jLabel26.setText(resourceMap.getString("jLabel26.text")); // NOI18N
        jLabel26.setName("jLabel26"); // NOI18N
        jPanel2.add(jLabel26);
        jLabel26.setBounds(170, 480, 170, 30);

        jLabel27.setBackground(resourceMap.getColor("jLabel14.background")); // NOI18N
        jLabel27.setForeground(resourceMap.getColor("jLabel14.foreground")); // NOI18N
        jLabel27.setText(resourceMap.getString("jLabel27.text")); // NOI18N
        jLabel27.setName("jLabel27"); // NOI18N
        jPanel2.add(jLabel27);
        jLabel27.setBounds(170, 520, 190, 30);

        jLabel29.setIcon(resourceMap.getIcon("jLabel29.icon")); // NOI18N
        jLabel29.setText(resourceMap.getString("jLabel29.text")); // NOI18N
        jLabel29.setName("jLabel29"); // NOI18N
        jPanel2.add(jLabel29);
        jLabel29.setBounds(-130, -10, 740, 810);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        Showinformation sh=new Showinformation(dt,pd);
        sh.setVisible(true);
        update u=new update(pd,dt);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public String id=new String();
    public String fullname=new String();
    public String password=new String();
    public String Securityword=new String();
    public String gender=new String();
    public String email=new String();
    public String district=new String();
    public String contact=new String();
    public String semester=new String();
    public String state=new String();
    public String date=new String();
    public String firstname=new String();
    public String lastname=new String();
    public String mid=new String();
    public String year=new String();
/*
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
*/
    private javax.swing.JLabel jLabel28;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    public javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel16;
    public javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
     private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel20;
    public javax.swing.JLabel jLabel21;
    public javax.swing.JLabel jLabel22;
    public javax.swing.JLabel jLabel23;
    public javax.swing.JLabel jLabel24;
    public javax.swing.JLabel jLabel25;
    public javax.swing.JLabel jLabel26;
    public javax.swing.JLabel jLabel27;
     private javax.swing.JLabel jLabel29;
    public javax.swing.JTextField jTextField1;
    public javax.swing.JTextField jTextField10;
    public javax.swing.JTextField jTextField2;
    public javax.swing.JTextField jTextField3;
    public javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
}
