/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Showinformation.java
 *
 * Created on Dec 30, 2015, 2:40:35 AM
 */

package projectdemo;
import java.sql.*;
/**
 *
 * @author Rakibul
 */
public class Showinformation extends javax.swing.JFrame {
public DatabaseTest dt;
ProjectDemoView pd;
//public String NID=new String();
//public String Password=new String();
    /** Creates new form Showinformation */
    public Showinformation(DatabaseTest dt,ProjectDemoView pd) {
        this.dt=dt;
        this.pd=pd;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N
        getContentPane().setLayout(null);

        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(null);

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(projectdemo.ProjectDemoApp.class).getContext().getResourceMap(Showinformation.class);
        jButton1.setFont(resourceMap.getFont("jButton2.font")); // NOI18N
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(20, 80, 100, 30);

        jButton2.setFont(resourceMap.getFont("jButton2.font")); // NOI18N
        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N
        jPanel1.add(jButton2);
        jButton2.setBounds(130, 80, 113, 30);

        jButton3.setFont(resourceMap.getFont("jButton2.font")); // NOI18N
        jButton3.setText(resourceMap.getString("jButton3.text")); // NOI18N
        jButton3.setName("jButton3"); // NOI18N
        jPanel1.add(jButton3);
        jButton3.setBounds(250, 80, 160, 30);

        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(70, 20, 310, 22);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 420, 150);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  //      ProjectDemoView p=new ProjectDemoView();
        view v=new view();
        this.setVisible(false);
        v.setVisible(true);
        try{
        //ResultSet rs=dt.dbc.searchDB("select username from sdb where NID='"+id+"'");
             ResultSet rs=dt.dbc.searchDB("select * from sdb where NID='"+pd.NID+"' and Password='"+pd.password+"'");
        while(rs.next())
        {
            v.id = rs.getString("NID");
            v.username = rs.getString("Username");
            v.password = rs.getString("Password");
            v.jTextField1.setText(v.id);
            v.jTextField2.setText(v.username);
            v.jTextField3.setText(v.password);
        }
       }
       catch(Exception e){
            System.out.println("ping");
        }// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
   /* public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
               new Showinformation().setVisible(true);
            }
        });

    }
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
