/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Showinformation.java
 *
 * Created on Dec 30, 2015, 2:40:35 AM
 */

package projectdemo;
import java.sql.*;
/**
 *
 * @author Rakibul
 */
public class showin extends javax.swing.JFrame {
public DatabaseTest dt;
ProjectDemoView pd;
//public String NID=new String();
//public String Password=new String();
    /** Creates new form Showinformation */
    public showin(DatabaseTest dt,ProjectDemoView pd) {
        this.dt=dt;
        this.pd=pd;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(projectdemo.ProjectDemoApp.class).getContext().getResourceMap(showin.class);
        jPanel1.setBackground(resourceMap.getColor("jPanel1.background")); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(null);

        jButton1.setFont(resourceMap.getFont("jButton2.font")); // NOI18N
        jButton1.setForeground(resourceMap.getColor("jButton1.foreground")); // NOI18N
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(20, 80, 100, 30);

        jButton2.setFont(resourceMap.getFont("jButton2.font")); // NOI18N
        jButton2.setForeground(resourceMap.getColor("jButton1.foreground")); // NOI18N
        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N
        jPanel1.add(jButton2);
        jButton2.setBounds(130, 80, 113, 30);

        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setForeground(resourceMap.getColor("jLabel1.foreground")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(70, 20, 310, 22);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  //      ProjectDemoView p=new ProjectDemoView();
        view v=new view(dt,pd);
        this.setVisible(false);
        v.setVisible(true);
        try{
        //ResultSet rs=dt.dbc.searchDB("select username from sdb where NID='"+id+"'");
             ResultSet rs=dt.dbc.searchDB("select * from sdb where NID='"+pd.NID+"' and Password='"+pd.password+"'");
        while(rs.next())
        {
            v.id = rs.getString("NID");
            v.username = rs.getString("Username");
            v.password = rs.getString("Password");
            v.gender = rs.getString("gender");
            v.contact = rs.getString("contact");
            v.age = rs.getString("age");
            v.securityword = rs.getString("securityword");
            v.jTextField1.setText(v.username);
            v.jTextField2.setText(v.id);
            v.jTextField3.setText(v.password);
   
            v.jTextField4.setText(v.securityword);
            v.jTextField5.setText(v.gender);
            v.jTextField6.setText(v.contact);
            v.jTextField7.setText(v.age);
        }
       }
       catch(Exception e){
            System.out.println("ping");
        }// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
   /* public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
               new Showinformation().setVisible(true);
            }
        });

    }
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
